spring:
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google
            client-id: 649187997356-ntrlr7i8iabi69o20h3h0crgrpgbgmbp.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          naver:
            client-id: XK_yhb8DoyNvji4gWGMd
            client-secret: wr71hB9BkC
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response